# Lab | Chains in LangChain

## Outline

* LLMChain
* Sequential Chains
  * SimpleSequentialChain
  * SequentialChain
* Router Chain

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [1]:
import os

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

OPENAI_API_KEY  = os.getenv('OPENAI_API_KEY')
HUGGINGFACEHUB_API_TOKEN = os.getenv('HUGGINGFACEHUB_API_TOKEN')

In [5]:
#!pip install pandas

In [2]:
import pandas as pd
df = pd.read_csv('./data/Data.csv')

In [3]:
df.head()

,Product,Review
0,Queen Size Sheet Set,I ordered a king size set. My only criticism w...
1,Waterproof Phone Pouch,"I loved the waterproof sac, although the openi..."
2,Luxury Air Mattress,This mattress had a small hole in the top of i...
3,Pillows Insert,This is the best throw pillow fillers on Amazo...
4,Milk Frother Handheld\r\n,I loved this product. But they only seem to l...

## LLMChain

In [4]:
!pip install langchain_community

Collecting langchain_community
  Downloading langchain_community-0.3.27-py3-none-any.whl.metadata (2.9 kB)
Collecting langchain-core<1.0.0,>=0.3.66 (from langchain_community)
  Downloading langchain_core-0.3.68-py3-none-any.whl.metadata (5.8 kB)
Collecting langchain<1.0.0,>=0.3.26 (from langchain_community)
  Downloading langchain-0.3.26-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (2.0.34)
Requirement already satisfied: requests<3,>=2 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (6.0.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (3.10.5)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (8.2.3)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (2.6.1)
Collecting langsmith>=0.1.125 (from langchain_community)
  Downloading langsmith-0.4.5-py3-none-any.whl.metadata (15 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: numpy>=1.26.2 in c:\users\lain\anaconda3\lib\site-packages (from langchain_community) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\lain\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\lain\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\lain\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\lain\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\lain\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\lain\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.11.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<1.0.0,>=0.3.8 (from langchain<1.0.0,>=0.3.26->langchain_community)
  Downloading langchain_text_splitters-0.3.8-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\lain\anaconda3\lib\site-packages (from langchain<1.0.0,>=0.3.26->langchain_community) (2.8.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.66->langchain_community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.66->langchain_community) (24.1)
Requirement already satisfied: typing-extensions>=4.7 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.66->langchain_community) (4.11.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.1.125->langchain_community) (0.27.0)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.1.125->langchain_community) (3.10.16)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.1.125->langchain_community) (0.23.0)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\lain\anaconda3\lib\site-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain_community) (0.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lain\anaconda3\lib\site-packages (from requests<3,>=2->langchain_community) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lain\anaconda3\lib\site-packages (from requests<3,>=2->langchain_community) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lain\anaconda3\lib\site-packages (from requests<3,>=2->langchain_community) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lain\anaconda3\lib\site-packages (from requests<3,>=2->langchain_community) (2025.4.26)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lain\anaconda3\lib\site-packages (from SQLAlchemy<3,>=1.4->langchain_community) (3.0.1)
Requirement already satisfied: anyio in c:\users\lain\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\users\lain\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (1.0.2)
Requirement already satisfied: sniffio in c:\users\lain\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\lain\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain_community) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\lain\anaconda3\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.66->langchain_community) (2.1)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\lain\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.26->langchain_community) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\lain\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.26->langchain_community) (2.20.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\lain\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community) (1.0.0)
Downloading langchain_community-0.3.27-py3-none-any.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 14.5 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.1-py3-none-any.whl (8.1 kB)
Downloading langchain-0.3.26-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 16.0 MB/s eta 0:00:00
Downloading langchain_core-0.3.68-py3-none-any.whl (441 kB)
Downloading langsmith-0.4.5-py3-none-any.whl (367 kB)
Downloading langchain_text_splitters-0.3.8-py3-none-any.whl (32 kB)
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Installing collected packages: typing-inspect, marshmallow, httpx-sse, dataclasses-json, langsmith, langchain-core, langchain-text-splitters, langchain, langchain_community
Successfully installed dataclasses-json-0.6.7 httpx-sse-0.4.1 langchain-0.3.26 langchain-core-0.3.68 langchain-text-splitters-0.3.8 langchain_community-0.3.27 langsmith-0.4.5 marshmallow-3.26.1 typing-inspect-0.9.0

In [6]:
!pip install langchain_openai

Collecting langchain_openai
  Downloading langchain_openai-0.3.28-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.68 in c:\users\lain\anaconda3\lib\site-packages (from langchain_openai) (0.3.68)
Collecting openai<2.0.0,>=1.86.0 (from langchain_openai)
  Downloading openai-1.96.0-py3-none-any.whl.metadata (29 kB)
Collecting tiktoken<1,>=0.7 (from langchain_openai)
  Downloading tiktoken-0.9.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
Requirement already satisfied: langsmith>=0.3.45 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (0.4.5)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (8.2.3)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (1.33)
Requirement already satisfied: PyYAML>=5.3 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (6.0.1)
Requirement already satisfied: packaging<25,>=23.2 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (24.1)
Requirement already satisfied: typing-extensions>=4.7 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (4.11.0)
Requirement already satisfied: pydantic>=2.7.4 in c:\users\lain\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.68->langchain_openai) (2.8.2)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\lain\anaconda3\lib\site-packages (from openai<2.0.0,>=1.86.0->langchain_openai) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\lain\anaconda3\lib\site-packages (from openai<2.0.0,>=1.86.0->langchain_openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\lain\anaconda3\lib\site-packages (from openai<2.0.0,>=1.86.0->langchain_openai) (0.27.0)
Requirement already satisfied: jiter<1,>=0.4.0 in c:\users\lain\anaconda3\lib\site-packages (from openai<2.0.0,>=1.86.0->langchain_openai) (0.10.0)
Requirement already satisfied: sniffio in c:\users\lain\anaconda3\lib\site-packages (from openai<2.0.0,>=1.86.0->langchain_openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\lain\anaconda3\lib\site-packages (from openai<2.0.0,>=1.86.0->langchain_openai) (4.66.5)
Requirement already satisfied: regex>=2022.1.18 in c:\users\lain\anaconda3\lib\site-packages (from tiktoken<1,>=0.7->langchain_openai) (2024.9.11)
Requirement already satisfied: requests>=2.26.0 in c:\users\lain\anaconda3\lib\site-packages (from tiktoken<1,>=0.7->langchain_openai) (2.32.3)
Requirement already satisfied: idna>=2.8 in c:\users\lain\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.86.0->langchain_openai) (3.7)
Requirement already satisfied: certifi in c:\users\lain\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.86.0->langchain_openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\lain\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.86.0->langchain_openai) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\lain\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2.0.0,>=1.86.0->langchain_openai) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\lain\anaconda3\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.68->langchain_openai) (2.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.68->langchain_openai) (3.10.16)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.68->langchain_openai) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in c:\users\lain\anaconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.68->langchain_openai) (0.23.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\lain\anaconda3\lib\site-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.68->langchain_openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\lain\anaconda3\lib\site-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.68->langchain_openai) (2.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lain\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken<1,>=0.7->langchain_openai) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lain\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken<1,>=0.7->langchain_openai) (2.2.3)
Requirement already satisfied: colorama in c:\users\lain\anaconda3\lib\site-packages (from tqdm>4->openai<2.0.0,>=1.86.0->langchain_openai) (0.4.6)
Downloading langchain_openai-0.3.28-py3-none-any.whl (70 kB)
Downloading openai-1.96.0-py3-none-any.whl (757 kB)
   ---------------------------------------- 0.0/757.1 kB ? eta -:--:--
   --------------------------------------- 757.1/757.1 kB 16.0 MB/s eta 0:00:00
Downloading tiktoken-0.9.0-cp312-cp312-win_amd64.whl (894 kB)
   ---------------------------------------- 0.0/894.9 kB ? eta -:--:--
   --------------------------------------- 894.9/894.9 kB 13.5 MB/s eta 0:00:00
Installing collected packages: tiktoken, openai, langchain_openai
  Attempting uninstall: openai
    Found existing installation: openai 1.82.1
    Uninstalling openai-1.82.1:
      Successfully uninstalled openai-1.82.1
Successfully installed langchain_openai-0.3.28 openai-1.96.0 tiktoken-0.9.0

In [7]:
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain

In [11]:
#Replace None by your own value and justify
llm = ChatOpenAI(temperature=0.5) # I choosed this temperature because I dont want the model to be too creativer

In [9]:
df.head()

,Product,Review
0,Queen Size Sheet Set,I ordered a king size set. My only criticism w...
1,Waterproof Phone Pouch,"I loved the waterproof sac, although the openi..."
2,Luxury Air Mattress,This mattress had a small hole in the top of i...
3,Pillows Insert,This is the best throw pillow fillers on Amazo...
4,Milk Frother Handheld\r\n,I loved this product. But they only seem to l...

In [15]:
prompt = ChatPromptTemplate.from_template( #Write a query that would take a variable to describe any product
 "Write a short description based on real user experience about the following product: {product}"
)

In [13]:

chain = LLMChain(llm=llm, prompt=prompt)

C:\Users\Lain\AppData\Local\Temp\ipykernel_18724\546483037.py:1: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  chain = LLMChain(llm=llm, prompt=prompt)

In [16]:
product = "Pillows Insert"
chain.run(product)

"I recently purchased the pillow insert and I am extremely satisfied with the quality. The insert is soft yet supportive, providing the perfect amount of comfort for a good night's sleep. The size was also perfect for my standard pillowcases. I highly recommend this product to anyone in need of a comfortable and durable pillow insert."

## SimpleSequentialChain

In [17]:
from langchain.chains import SimpleSequentialChain

In [18]:
llm = ChatOpenAI(temperature=0.9)

# prompt template 1
first_prompt = ChatPromptTemplate.from_template(
    "Write a short description based on real user experience about the following product: {product}"
)

# Chain 1
chain_one = LLMChain(llm=llm, prompt=first_prompt)

In [22]:

# prompt template 2
second_prompt = ChatPromptTemplate.from_template(
    "Write a negative blog style post based on the following description : {text}"
)
# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt)

In [25]:

# prompt template 2
second_prompt = ChatPromptTemplate.from_template(
    "Write a recipe post based on the following description : {text}"
)
# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt)

In [26]:
overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],
                                             verbose=True
                                            )

In [24]:
overall_simple_chain.run(product)

> Entering new SimpleSequentialChain chain...
I recently purchased a set of pillow inserts and I am extremely satisfied with the quality of the product. The inserts are fluffy and provide excellent support for a comfortable night's sleep. They fit perfectly into my pillow covers and have helped to enhance the overall look of my bedding. I would highly recommend these pillow inserts to anyone looking to upgrade their pillows for a more luxurious and relaxing sleep experience.
I recently purchased a set of pillow inserts and I have to say, I am extremely disappointed with the quality of the product. Despite the description claiming they are fluffy and provide excellent support, I found them to be lumpy and uncomfortable to sleep on.

Not only that, but they did not fit properly into my pillow covers, leaving them looking misshapen and sloppy. Instead of enhancing the look of my bedding, they made it look cheap and unkempt.

I would not recommend these pillow inserts to anyone looking to upgrade their pillows for a more luxurious and relaxing sleep experience. Save your money and look elsewhere for a better quality product.

> Finished chain.

'I recently purchased a set of pillow inserts and I have to say, I am extremely disappointed with the quality of the product. Despite the description claiming they are fluffy and provide excellent support, I found them to be lumpy and uncomfortable to sleep on.\n\nNot only that, but they did not fit properly into my pillow covers, leaving them looking misshapen and sloppy. Instead of enhancing the look of my bedding, they made it look cheap and unkempt.\n\nI would not recommend these pillow inserts to anyone looking to upgrade their pillows for a more luxurious and relaxing sleep experience. Save your money and look elsewhere for a better quality product.'

In [27]:
overall_simple_chain.run(product)

> Entering new SimpleSequentialChain chain...
I recently purchased a set of pillow inserts for my decorative throw pillows, and I couldn't be happier with the quality. The inserts are plush and provide the perfect amount of support, making my pillows look full and inviting. The material is soft and durable, and they fit perfectly into my pillow covers. I would highly recommend these pillow inserts to anyone looking to upgrade their home decor with a simple and affordable addition.
Ingredients:
- Set of pillow inserts
- Decorative throw pillows

Instructions:
1. Start by removing your old pillow inserts from your decorative throw pillows.
2. Take your new pillow inserts and fluff them up to ensure they are nice and plush.
3. Carefully insert the new pillow inserts into your pillow covers, making sure they fit snugly.
4. Fluff and adjust the inserts as needed to ensure they fill out the pillow covers completely.
5. Place your newly refreshed decorative throw pillows on your couch, bed, or any other seating area in your home.
6. Sit back and enjoy your upgraded home decor with your new plush and supportive pillow inserts.

I hope you enjoy your new pillow inserts as much as I have! They truly make a difference in the look and feel of your decorative throw pillows.

> Finished chain.

'Ingredients:\n- Set of pillow inserts\n- Decorative throw pillows\n\nInstructions:\n1. Start by removing your old pillow inserts from your decorative throw pillows.\n2. Take your new pillow inserts and fluff them up to ensure they are nice and plush.\n3. Carefully insert the new pillow inserts into your pillow covers, making sure they fit snugly.\n4. Fluff and adjust the inserts as needed to ensure they fill out the pillow covers completely.\n5. Place your newly refreshed decorative throw pillows on your couch, bed, or any other seating area in your home.\n6. Sit back and enjoy your upgraded home decor with your new plush and supportive pillow inserts.\n\nI hope you enjoy your new pillow inserts as much as I have! They truly make a difference in the look and feel of your decorative throw pillows.'

**Repeat the above twice for different products**

## SequentialChain

In [28]:
from langchain.chains import SequentialChain

In [44]:
llm = ChatOpenAI(temperature=0.9)


first_prompt = ChatPromptTemplate.from_template(
    #This prompt should translate a review
  "Translate the given review  {review} to catalan language"
)

chain_one = LLMChain(llm=llm, prompt=first_prompt, 
                     output_key="catalan_review" #Give a name to your output
                    )

In [45]:
second_prompt = ChatPromptTemplate.from_template(
    #Write a promplt to summarize a review
    "Summarize the given review {review} to just one sentence "
)

chain_two = LLMChain(llm=llm, prompt=second_prompt, 
                     output_key="summarize_review" #give a name to this output
                    )

In [46]:
# prompt template 3: translate to english or other language
third_prompt = ChatPromptTemplate.from_template(
    "translate the given text to indonesian: {review}"
)
# chain 3: input= Review and output= language
chain_three = LLMChain(llm=llm, prompt=third_prompt,
                       output_key="translation"
                      )

In [47]:

# prompt template 4: follow up message that take as inputs the two previous prompts' variables
fourth_prompt = ChatPromptTemplate.from_template(
        "Write a friendly follow-up message to the user including these insights:" \
        "{catalan_review}, {summarize_review} and {translation}"
)
chain_four = LLMChain(llm=llm, prompt=fourth_prompt,
                      output_key="followup-message"
                     )

In [50]:
# overall_chain: input= Review 
# and output= English_Review,summary, followup_message
overall_chain = SequentialChain(
    chains=[chain_one, chain_two, chain_three, chain_four],
    input_variables=["review"],
    output_variables=["catalan_review", "summarize_review", "translation", "followup-message"],
    verbose=True
)

In [51]:
review = df.Review[5]
overall_chain(review)

> Entering new SequentialChain chain...

> Finished chain.

{'review': "Je trouve le goût médiocre. La mousse ne tient pas, c'est bizarre. J'achète les mêmes dans le commerce et le goût est bien meilleur...\r\nVieux lot ou contrefaçon !?",
 'catalan_review': 'Trobo el gust mediocre. La escuma no es manté, és estrany. Compro els mateixos al comerç i el gust és molt millor... Vell lot o falsificació!?',
 'summarize_review': 'Le goût est médiocre et la mousse ne tient pas, suggérant peut-être un vieux lot ou une contrefaçon.',
 'translation': 'Saya menemukan rasanya biasa saja. Busanya tidak tahan, aneh. Saya membeli yang sama di toko dan rasanya jauh lebih baik...\nStok lama atau barang palsu!?',
 'followup-message': 'Hi there! Thank you for sharing your insights about the product. It sounds like you may have received an old batch or a counterfeit item. I recommend reaching out to the seller or manufacturer to address your concerns and ensure you are getting the quality product you expect. I hope you are able to resolve this issue and enjoy the product as it should be. Have a great day!'}

**Repeat the above twice for different products or reviews**

## Router Chain

In [52]:
physics_template = """You are a very smart physics professor. \
You are great at answering questions about physics in a concise\
and easy to understand manner. \
When you don't know the answer to a question you admit\
that you don't know.

Here is a question:
{input}"""


math_template = """You are a very good mathematician. \
You are great at answering math questions. \
You are so good because you are able to break down \
hard problems into their component parts, 
answer the component parts, and then put them together\
to answer the broader question.

Here is a question:
{input}"""

history_template = """You are a very good historian. \
You have an excellent knowledge of and understanding of people,\
events and contexts from a range of historical periods. \
You have the ability to think, reflect, debate, discuss and \
evaluate the past. You have a respect for historical evidence\
and the ability to make use of it to support your explanations \
and judgements.

Here is a question:
{input}"""


computerscience_template = """ You are a successful computer scientist.\
You have a passion for creativity, collaboration,\
forward-thinking, confidence, strong problem-solving capabilities,\
understanding of theories and algorithms, and excellent communication \
skills. You are great at answering coding questions. \
You are so good because you know how to solve a problem by \
describing the solution in imperative steps \
that a machine can easily interpret and you know how to \
choose a solution that has a good balance between \
time complexity and space complexity. 

Here is a question:
{input}"""

biology_template = """You are an excellent biologist. \
You have a deep understanding of living organisms, \
from the molecular and cellular level to entire ecosystems. \
You are skilled at observing patterns in nature, analyzing biological data, \
and explaining complex processes like evolution, genetics, physiology, and ecology. \
You can clearly communicate how life functions and adapts, \
and you make connections between different biological concepts \
to answer challenging questions.

Here is a question:
{input}"""

In [53]:
prompt_infos = [
    {
        "name": "physics", 
        "description": "Good for answering questions about physics", 
        "prompt_template": physics_template
    },
    {
        "name": "math", 
        "description": "Good for answering math questions", 
        "prompt_template": math_template
    },
    {
        "name": "History", 
        "description": "Good for answering history questions", 
        "prompt_template": history_template
    },
    {
        "name": "computer science", 
        "description": "Good for answering computer science questions", 
        "prompt_template": computerscience_template
    },
    {
        "name": "biology",
        "description": "Good for answering biology questions",
        "prompt_template": biology_template
    }
]

In [54]:
from langchain.chains.router import MultiPromptChain
from langchain.chains.router.llm_router import LLMRouterChain,RouterOutputParser
from langchain.prompts import PromptTemplate

In [55]:
llm = ChatOpenAI(temperature=0)

In [56]:
destination_chains = {}
for p_info in prompt_infos:
    name = p_info["name"]
    prompt_template = p_info["prompt_template"]
    prompt = ChatPromptTemplate.from_template(template=prompt_template)
    chain = LLMChain(llm=llm, prompt=prompt)
    destination_chains[name] = chain  
    
destinations = [f"{p['name']}: {p['description']}" for p in prompt_infos]
destinations_str = "\n".join(destinations)

In [60]:
default_prompt = ChatPromptTemplate.from_template("{input}")
default_chain = LLMChain(llm=llm, prompt=default_prompt)

In [61]:
MULTI_PROMPT_ROUTER_TEMPLATE = """Given a raw text input to a \
language model select the model prompt best suited for the input. \
You will be given the names of the available prompts and a \
description of what the prompt is best suited for. \
You may also revise the original input if you think that revising\
it will ultimately lead to a better response from the language model.

<< FORMATTING >>
Return a markdown code snippet with a JSON object formatted to look like:
```json
{{{{
    "destination": string \ name of the prompt to use or "DEFAULT"
    "next_inputs": string \ a potentially modified version of the original input
}}}}
```

REMEMBER: "destination" MUST be one of the candidate prompt \
names specified below OR it can be "DEFAULT" if the input is not\
well suited for any of the candidate prompts.
REMEMBER: "next_inputs" can just be the original input \
if you don't think any modifications are needed.

<< CANDIDATE PROMPTS >>
{destinations}

<< INPUT >>
{{input}}

<< OUTPUT (remember to include the ```json)>>"""

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
C:\Users\Lain\AppData\Local\Temp\ipykernel_18724\2160379643.py:1: SyntaxWarning: invalid escape sequence '\ '
  MULTI_PROMPT_ROUTER_TEMPLATE = """Given a raw text input to a \

In [62]:
router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
    destinations=destinations_str
)
router_prompt = PromptTemplate(
    template=router_template,
    input_variables=["input"],
    output_parser=RouterOutputParser(),
)

router_chain = LLMRouterChain.from_llm(llm, router_prompt)

In [63]:
chain = MultiPromptChain(router_chain=router_chain, 
                         destination_chains=destination_chains, 
                         default_chain=default_chain, verbose=True
                        )

C:\Users\Lain\AppData\Local\Temp\ipykernel_18724\3038952769.py:1: LangChainDeprecationWarning: Please see migration guide here for recommended implementation: https://python.langchain.com/docs/versions/migrating_chains/multi_prompt_chain/
  chain = MultiPromptChain(router_chain=router_chain,

In [65]:
chain.run("What is black body radiation?")

> Entering new MultiPromptChain chain...
physics: {'input': 'What is black body radiation?'}
> Finished chain.

"Black body radiation refers to the electromagnetic radiation emitted by a perfect absorber and emitter of radiation, known as a black body. A black body absorbs all radiation that falls on it and emits radiation at all wavelengths. The spectrum of black body radiation is continuous and depends only on the temperature of the body. This phenomenon is described by Planck's law, which states that the intensity of radiation emitted by a black body at a given wavelength is proportional to the temperature of the body and the wavelength raised to the fifth power. Black body radiation is important in understanding the behavior of objects at high temperatures and is a key concept in the field of thermal physics."

In [66]:
chain.run("what is 2 + 2")

> Entering new MultiPromptChain chain...
math: {'input': 'what is 2 + 2'}
> Finished chain.

'The answer to 2 + 2 is 4.'

In [67]:
chain.run("Why does every cell in our body contain DNA?")

> Entering new MultiPromptChain chain...
biology: {'input': 'Why does every cell in our body contain DNA?'}
> Finished chain.

'Every cell in our body contains DNA because DNA is the genetic material that carries the instructions for the development, functioning, and reproduction of all living organisms. DNA contains the information needed to build and maintain an organism, including the proteins that make up our cells and tissues. \n\nHaving DNA in every cell ensures that each cell has the necessary genetic information to carry out its specific functions and to replicate itself accurately during cell division. This ensures that the genetic information is passed on to the next generation of cells. \n\nAdditionally, DNA is constantly being used by cells to carry out processes such as protein synthesis, cell division, and repair. Having DNA in every cell allows for the coordination of these processes and ensures that the organism functions properly as a whole. \n\nIn summary, every cell in our body contains DNA because it is essential for the proper functioning and development of all living organisms.'

**Repeat the above at least once for different inputs and chains executions - Be creative!**